#########
#
# workshop-template-b, evanwill
# a Jekyll template for a simple workshop website
# https://github.com/evanwill/workshop-template-b
#
#########

#######
# SITE SETTINGS
#
# title appears in the header
title: HyperSCI
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Bootstrap Icons in _includes/bootstrap-icons
# find names on https://icons.getbootstrap.com/
# some options: code-slash file-code gear tools lightblub book bookmark-star
title-icon: book
# description, keywords, and image for meta tags
# these do not visibility appear on the pages, but used for SEO
description: "Website for HyperSCI: 1st International Workshop on Theory and Applications of Hypernetwork Science"
keywords: "workshops, websites, gh-pages, jekyll, network science"
# featured-image is added to metadata tags for social media sharing
# use a relative path to image in this repository or full URL
# add search box to footer? true/false
search: true

# author settings for cc-by, appears in the footer and credits
author: Andrea Failla
# your github username for link [optional]
github_username: andreafailla
# year or date published
pub_year: 2024
# location of code, the full url to your github repository
source-code: https://github.com/hyperSCI-workshop/hyperSCI-workshop

##########
# URL VARIABLES [optional!!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
# When using github pages just leave these blank!
#
# use url for the domain, e.g. https://evanwill.github.io
# on gh-pages follow the pattern: https://username.github.io
url:
# use baseurl to add subsection of the domain, e.g. /workshop-template-b
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
baseurl:


##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
# ignore stuff
exclude: [README.md, LICENSE, assets/lib/README.md]
# Build settings
markdown: kramdown
